# Generated by Django 6.0.2 on 2026-02-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbit',
            name='parent',
        ),
        migrations.AddField(
            model_name='rabbit',
            name='buck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathered', to='db.rabbit'),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='doe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters', to='db.rabbit'),
        ),
    ]
