# Generated by Django 6.0.2 on 2026-02-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_rabbit_parent_rabbit_buck_rabbit_doe'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='temprament',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
