# Generated by Django 6.0.2 on 2026-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rabbit_note_rabbit_temprament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='image',
            field=models.ImageField(default='rabbits/Default.png', upload_to='rabbits/'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
