# Generated by Django 6.0.2 on 2026-03-11 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_rabbit_date_of_birth_alter_rabbit_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RabbitImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='rabbits/')),
                ('rabbit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rabbit', to='db.rabbit')),
            ],
        ),
    ]
