# Generated by Django 6.0.2 on 2026-03-13 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rabbitimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitimage',
            name='rabbit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbit', to='db.rabbit'),
        ),
    ]
