# Generated by Django 6.0.2 on 2026-03-13 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_rabbitimage_rabbit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RabbitLitter',
            fields=[
                ('litter_id', models.AutoField(primary_key=True, serialize=False)),
                ('litter_number', models.IntegerField()),
                ('litter_date', models.DateField(blank=True, null=True)),
                ('buck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litter_buck', to='db.rabbit')),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litter_doe', to='db.rabbit')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.rabbit')),
            ],
        ),
    ]
