# Generated by Django 6.0.2 on 2026-03-13 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_rabbitlitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitlitter',
            name='buck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litter_buck', to='db.rabbit'),
        ),
        migrations.AlterField(
            model_name='rabbitlitter',
            name='doe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litter_doe', to='db.rabbit'),
        ),
    ]
