# Generated by Django 6.0.2 on 2026-03-30 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_rabbitlitter_buck_alter_rabbitlitter_doe'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rabbitlitter',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RabbitAbandoned',
            fields=[
                ('abandon_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('foster_mom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fostered_kits', to='db.rabbit')),
                ('rabbit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abandonment_details', to='db.rabbit')),
            ],
        ),
    ]
