# Generated by Django 6.0.2 on 2026-03-30 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_rabbit_abandoned_rabbitlitter_abandoned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RabbitWeight',
            fields=[
                ('weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='db.rabbit')),
            ],
        ),
    ]
