# Generated by Django 6.0.2 on 2026-04-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_rabbitweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='RabbitFeed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feed_number', models.IntegerField()),
                ('date', models.DateField()),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='db.rabbit')),
            ],
        ),
    ]
