# Generated by Django 6.0.2 on 2026-05-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_rabbitfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitfeed',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='RabbitFeedNumbers',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_feeds', models.IntegerField()),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_feeds', to='db.rabbit')),
            ],
        ),
    ]
