# Generated by Django 6.0.2 on 2026-02-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='rabbits/')),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('M', 'Buck'), ('F', 'Doe'), ('U', 'Unsexed')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.BooleanField(default=False)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('cause_of_death', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='group_view.rabbit')),
            ],
        ),
    ]
