# Generated by Django 6.0.2 on 2026-02-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunny_view', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rabbit',
        ),
    ]
