# Generated by Django 6.0.2 on 2026-02-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='cause_of_death',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='image',
            field=models.ImageField(null=True, upload_to='rabbits/'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='sex',
            field=models.CharField(choices=[('M', 'Buck'), ('F', 'Doe'), ('U', 'Unsexed')], max_length=1),
        ),
    ]
