# Generated by Django 6.0.2 on 2026-02-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rabbit_cause_of_death_rabbit_date_of_death_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rabbit',
        ),
    ]
